import os
import uuid
import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle,
)
from reportlab.lib.units import inch

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)


class PDFReport:

    def __init__(self):

        Path("reports").mkdir(exist_ok=True)

        self.styles = getSampleStyleSheet()

        self.title_style = ParagraphStyle(
            "AEGISTitle",
            parent=self.styles["Heading1"],
            fontSize=24,
            alignment=TA_CENTER,
            textColor=colors.darkblue,
            spaceAfter=20,
        )

        self.heading_style = ParagraphStyle(
            "Heading",
            parent=self.styles["Heading2"],
            textColor=colors.darkblue,
            spaceBefore=15,
            spaceAfter=8,
        )

        self.normal_style = self.styles["BodyText"]


    def add_heading(self, story, text):

        story.append(
            Paragraph(
                f"<b>{text}</b>",
                self.heading_style,
            )
        )

        story.append(Spacer(1, 8))


    def add_table(self, story, data):

        table = Table(
            data,
            colWidths=[2.4 * inch, 3.8 * inch],
        )

        table.setStyle(

            TableStyle(

                [

                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#ECECEC")),

                    ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),

                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),

                    ("TOPPADDING", (0, 0), (-1, -1), 6),

                    ("VALIGN", (0, 0), (-1, -1), "TOP"),

                ]

            )

        )

        story.append(table)

        story.append(Spacer(1, 12))


    def footer(self, canvas, doc):

        canvas.saveState()

        canvas.setFont("Helvetica", 9)

        canvas.drawString(

            40,
            20,
            "Generated by AEGIS Security Scanner",

        )

        canvas.drawRightString(

            560,
            20,
            f"Page {doc.page}",

        )

        canvas.restoreState()


    def generate(self, result, vt_result):
###################################################
        filename = f"{result['domain'].replace('.', '_')}.pdf"

        filepath = os.path.join(
            "reports",
            filename,
        )

        doc = SimpleDocTemplate(filepath)

        story = []

        report_id = str(uuid.uuid4())[:8].upper()

        scan_time = datetime.datetime.now().strftime(
            "%d-%m-%Y %H:%M:%S"
        )

        whois = result.get("whois") or {}
        ssl = result.get("ssl") or {}
        headers = result.get("headers") or {}
        technology = result.get("technology") or {}
        dns = result.get("dns") or {}
        ports = result.get("ports") or []

        # ==================================================
        # TITLE
        # ==================================================

        story.append(
            Paragraph(
                "AEGIS Security Assessment Report",
                self.title_style,
            )
        )

        story.append(
            Paragraph(
                "<b>Cyber Security Threat Assessment Report</b>",
                self.normal_style,
            )
        )

        story.append(Spacer(1, 20))

        # ==================================================
        # EXECUTIVE SUMMARY
        # ==================================================

        self.add_heading(
            story,
            "1. Executive Summary",
        )

        story.append(

            Paragraph(

                """
                This report was generated automatically by
                <b>AEGIS Security Scanner</b>.

                The assessment includes:

                • WHOIS Information<br/>
                • SSL Certificate Validation<br/>
                • VirusTotal Reputation Check<br/>
                • HTTP Security Header Analysis<br/>
                • Open Port Discovery<br/>
                • DNS Intelligence<br/>
                • Technology Detection<br/>
                • Overall Risk Assessment

                """,

                self.normal_style,

            )

        )

        story.append(Spacer(1, 15))

        # ==================================================
        # REPORT INFORMATION
        # ==================================================

        self.add_heading(
            story,
            "2. Report Information",
        )

        report_table = [

            ["Report ID", report_id],

            ["Generated", scan_time],

            ["Risk Score", f"{result['risk_score']}/100"],

            ["Threat Level", result["threat_level"]],

        ]

        self.add_table(
            story,
            report_table,
        )

        # ==================================================
        # TARGET INFORMATION
        # ==================================================

        self.add_heading(
            story,
            "3. Target Information",
        )

        target_table = [

            ["URL", result["url"]],

            ["Domain", result["domain"]],

            ["IP Address", result["ip"]],

        ]

        self.add_table(
            story,
            target_table,
        )

        # ==================================================
        # WHOIS INFORMATION
        # ==================================================

        self.add_heading(
            story,
            "4. WHOIS Information",
        )

        whois_table = [

            ["Registrar", whois.get("registrar", "Unknown")],

            ["Country", whois.get("country", "Unknown")],

        ]

        self.add_table(
            story,
            whois_table,
        )

        # ==================================================
        # SSL CERTIFICATE
        # ==================================================

        self.add_heading(
            story,
            "5. SSL Certificate",
        )

        ssl_table = [

            ["SSL Valid", ssl.get("valid", "Unknown")],

            ["Expiry Date", ssl.get("expires", "Unknown")],

        ]

        self.add_table(
            story,
            ssl_table,
        )
#############################################################
        # ==================================================
        # VIRUSTOTAL ANALYSIS
        # ==================================================

        self.add_heading(
            story,
            "6. VirusTotal Analysis",
        )

        vt_table = [

            ["Malicious", str(vt_result.get("malicious", 0))],

            ["Suspicious", str(vt_result.get("suspicious", 0))],

            ["Harmless", str(vt_result.get("harmless", 0))],

            ["Undetected", str(vt_result.get("undetected", 0))],

        ]

        self.add_table(
            story,
            vt_table,
        )

        # ==================================================
        # HTTP SECURITY HEADERS
        # ==================================================

        self.add_heading(
            story,
            "7. HTTP Security Headers",
        )

        security_headers = headers.get("headers", {})

        if security_headers:

            security_table = [
                ["Header", "Status"]
            ]

            for header, value in security_headers.items():

                if value != "Missing":
                    status = "Present"
                else:
                    status = "Missing"

                security_table.append(
                    [
                        header,
                        status,
                    ]
                )

            table = Table(
                security_table,
                colWidths=[4.2 * inch, 2.0 * inch],
            )

            table.setStyle(

                TableStyle(

                    [

                        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),

                        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#D9EAF7")),

                        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),

                        ("BOTTOMPADDING", (0,0), (-1,-1), 6),

                        ("TOPPADDING", (0,0), (-1,-1), 6),

                        ("VALIGN", (0,0), (-1,-1), "TOP"),

                    ]

                )

            )

            story.append(table)

            story.append(Spacer(1, 10))

        else:

            story.append(

                Paragraph(

                    "No HTTP Security Headers were detected.",

                    self.normal_style,

                )

            )

            story.append(Spacer(1, 10))

        story.append(

            Paragraph(

                f"<b>Header Score :</b> {headers.get('score',0)}/100",

                self.normal_style,

            )

        )

        story.append(Spacer(1, 15))
############################################################
        # ==================================================
        # OPEN PORTS
        # ==================================================

        self.add_heading(
            story,
            "8. Open Ports",
        )

        if ports:

            port_table = [
                ["Port", "Service"]
            ]

            for port in ports:

                port_table.append(
                    [
                        str(port.get("port", "Unknown")),
                        port.get("service", "Unknown"),
                    ]
                )

            table = Table(
                port_table,
                colWidths=[1.5 * inch, 4.5 * inch],
            )

            table.setStyle(

                TableStyle(

                    [

                        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),

                        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#D9EAF7")),

                        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),

                        ("BOTTOMPADDING", (0,0), (-1,-1), 6),

                        ("TOPPADDING", (0,0), (-1,-1), 6),

                    ]

                )

            )

            story.append(table)

        else:

            story.append(
                Paragraph(
                    "No open ports detected.",
                    self.normal_style,
                )
            )

        story.append(Spacer(1, 15))

        # ==================================================
        # DNS INTELLIGENCE
        # ==================================================

        self.add_heading(
            story,
            "9. DNS Intelligence",
        )

        dns_table = []

        if dns.get("A"):

            dns_table.append(
                [
                    "A Record",
                    "<br/>".join(dns["A"])
                ]
            )

        if dns.get("MX"):

            dns_table.append(
                [
                    "MX Record",
                    "<br/>".join(dns["MX"])
                ]
            )

        if dns.get("NS"):

            dns_table.append(
                [
                    "NS Record",
                    "<br/>".join(dns["NS"])
                ]
            )

        if dns.get("TXT"):

            dns_table.append(
                [
                    "TXT Records",
                    f"{len(dns['TXT'])} record(s)"
                ]
            )

        if dns.get("CNAME"):

            dns_table.append(
                [
                    "CNAME",
                    "<br/>".join(dns["CNAME"])
                ]
            )

        if dns_table:

            table = Table(
                dns_table,
                colWidths=[2.0 * inch, 4.0 * inch],
            )

            table.setStyle(

                TableStyle(

                    [

                        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),

                        ("BACKGROUND", (0,0), (0,-1), colors.HexColor("#ECECEC")),

                        ("BOTTOMPADDING", (0,0), (-1,-1), 6),

                        ("TOPPADDING", (0,0), (-1,-1), 6),

                    ]

                )

            )

            story.append(table)

        else:

            story.append(
                Paragraph(
                    "No DNS records found.",
                    self.normal_style,
                )
            )

        story.append(Spacer(1, 15))

        # ==================================================
        # TECHNOLOGY DETECTION
        # ==================================================

        self.add_heading(
            story,
            "10. Technology Detection",
        )

        technology_table = [

            [
                "Status",
                technology.get("status", "Unknown")
            ],

            [
                "Server",
                technology.get("server", "Unknown")
            ],

            [
                "Framework",
                ", ".join(
                    technology.get("framework", [])
                ) or "None"
            ],

            [
                "CMS",
                ", ".join(
                    technology.get("cms", [])
                ) or "None"
            ],

        ]

        self.add_table(
            story,
            technology_table,
        )
##########################################################
        # ==================================================
        # RISK ANALYSIS
        # ==================================================

        self.add_heading(
            story,
            "11. Risk Analysis",
        )

        risk_table = [

            [
                "Risk Score",
                f"{result['risk_score']}/100",
            ],

            [
                "Threat Level",
                result["threat_level"],
            ],

        ]

        self.add_table(
            story,
            risk_table,
        )

        # ==================================================
        # RECOMMENDATIONS
        # ==================================================

        self.add_heading(
            story,
            "12. Recommendations",
        )

        story.append(

            Paragraph(

                result["recommendation"],

                self.normal_style,

            )

        )

        story.append(Spacer(1, 20))

        # ==================================================
        # REPORT CONCLUSION
        # ==================================================

        self.add_heading(
            story,
            "Conclusion",
        )

        story.append(

            Paragraph(

                """
                This report was generated automatically by
                <b>AEGIS Security Scanner</b>.

                The findings presented in this report are
                intended to assist security professionals
                in identifying potential weaknesses in the
                target system.

                Manual verification is recommended before
                taking any remediation action.

                """,

                self.normal_style,

            )

        )

        story.append(Spacer(1, 20))

        story.append(

            Paragraph(

                "<b>AEGIS Security Scanner v1.0</b>",

                self.normal_style,

            )

        )

        # ==================================================
        # BUILD PDF
        # ==================================================

        doc.build(

            story,

            onFirstPage=self.footer,

            onLaterPages=self.footer,

        )

        return filepath